### ISSUE TITLE
Managing security with Azure Lighthouse and Azure Arc

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#18]
- 文章地址：[/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md)

**Comment by PiperLiu** [comment]
- 认领时间： 2020-01-09
- 认领人员： [PiperLiu](https://github.com/PiperLiu)
- 认领文章： [Managing security with Azure Lighthouse and Azure Arc](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md)
- 原文： [Managing security with Azure Lighthouse and Azure Arc](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md) By *Sonia Cuff* ©Microsoft on ‎‎‎11-26-2019 01:53 AM

**Comment by iamanother** [comment]
### 审阅认领: [Managing security with Azure Lighthouse and Azure Arc ] 


认领时间： 2020-01-09
认领人员： [王一帆](https://github.com/iamanother)
认领文章：   [Managing security with Azure Lighthouse and Azure](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md)
原文： [Managing security with Azure Lighthouse and Azure Arc](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md) By Sonia Cuff ©Microsoft on ‎‎‎11-26-2019 01:53 AM

@PiperLiu
