### ISSUE TITLE
Deploying Java EE apps to Azure: Part 2

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#19]
文章地址：[/content/cloud-advocate/2020-01/deploying-java-ee-apps-to-azure-part-2.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/deploying-java-ee-apps-to-azure-part-2.md)

**Comment by XtaoBai** [comment]
认领时间： 2020-02-14
认领人员： Xtao Bai
认领文章： Deploying Java EE apps to Azure: Part 2
文章地址：[/content/cloud-advocate/2020-01/deploying-java-ee-apps-to-azure-part-2.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/deploying-java-ee-apps-to-azure-part-2.md)

**Comment by XtaoBai** [comment]
已提交 PR 等待审核
