### ISSUE TITLE
翻译认领: Managing security with Azure Lighthouse and Azure Arc

### ISSUE THREAD

**Issue by PiperLiu** [azureselected/azureselected#21]
- 认领时间： 2020-01-09
- 认领人员： [PiperLiu](https://github.com/PiperLiu)
- 认领文章： [Managing security with Azure Lighthouse and Azure Arc](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md)
- 原文： [Managing security with Azure Lighthouse and Azure Arc](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/Managing-security-with-Azure-Lighthouse-and-Azure-Arc/index.md) By *Sonia Cuff* ©Microsoft on ‎‎‎11-26-2019 01:53 AM

**Comment by shinyzhu** [comment]
#18 建议在同一个Issue下认领和审阅。根据Issue建分支来协作。

**Comment by PiperLiu** [comment]
收到，下次注意，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shiny"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 下午3:10
收件人:&nbsp;"azureselected/azureselected"<azureselected@noreply.github.com&gt;;
抄送:&nbsp;"Piper"<2940596912@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [azureselected/azureselected] 翻译认领: Managing security with Azure Lighthouse and Azure Arc (#21)




#18 建议在同一个Issue下认领和审阅。根据Issue建分支来协作。

**Comment by shinyzhu** [comment]
> 收到，下次注意，谢谢。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Shiny"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月9日(星期四) 下午3:10 收件人:&nbsp;"azureselected/azureselected"<azureselected@noreply.github.com&gt;; 抄送:&nbsp;"Piper"<2940596912@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [azureselected/azureselected] 翻译认领: Managing security with Azure Lighthouse and Azure Arc (#21) #18 建议在同一个Issue下认领和审阅。根据Issue建分支来协作。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不存在，大家讨论，找到最高效的协作方式。

**Comment by iamanother** [comment]
收到！
