### ISSUE TITLE
审阅认领: [Managing security with Azure Lighthouse and Azure Arc ]

### ISSUE THREAD

**Issue by iamanother** [azureselected/azureselected#22]
- 认领时间： 2020-01-09
- 认领人员： [王一帆](https://github.com/iamanother)
认领文章： Managing security with Azure Lighthouse and Azure Arc
原文： Managing security with Azure Lighthouse and Azure Arc By Sonia Cuff ©Microsoft on ‎‎‎11-26-2019 01:53 AM

**Comment by shinyzhu** [comment]
我建议一个文章在同一个Issue里面完成。这个可以在 #18  里面做。不知道大家有没有其他建议。

**Comment by iamanother** [comment]
Follow [#18](https://github.com/azureselected/azureselected/issues/18) instead.
