### ISSUE TITLE
翻译认领：Deploying Java EE apps to Azure: Part 3

### ISSUE THREAD

**Issue by yellow-pig** [azureselected/azureselected#27]
- 认领时间： 2020-01-20
- 认领人员： [ yellow_pig](https://github.com/yellow-pig)
- 认领文章： [Deploying Java EE apps to Azure: Part 3](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-01/deploying-java-ee-apps-to-azure-part-3.md)
- 原文： [Deploying Java EE apps to Azure: Part 3](https://techcommunity.microsoft.com/t5/itops-talk-blog/manage-multiple-azure-tenancies-with-azure-lighthouse/ba-p/833928) By *Sonia Cuff* ©Microsoft on ‎09-03-2019 02:00 AM

**Comment by shinyzhu** [comment]
@yellow-pig 我来催更啦。
