### ISSUE TITLE
How to learn Microsoft Azure in 2020

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#29]
原文：How to learn Microsoft Azure in 2020
链接：[/content/cloud-advocate/2020-01/how-to-learn-microsoft-azure-in-2020.md](https://github.com/azureselected/azureselected//blob/master/content/cloud-advocate/2020-01/how-to-learn-microsoft-azure-in-2020.md)

**Comment by msdz** [comment]
@shinyzhu 翻译认领：HOW TO LEARN MICROSOFT AZURE IN 2020
