### ISSUE TITLE
How to use GitHub Actions to deploy a virtual machine

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#30]
原文：How to use GitHub Actions to deploy a virtual machine
链接：[/content/cloud-advocate/2020-02/how-to-use-github-actions-to-deploy-an-azure-virtual-machine.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-02/how-to-use-github-actions-to-deploy-an-azure-virtual-machine.md)

**Comment by IannaZhou** [comment]
@shinyzhu 翻译认领：How to use GitHub Actions to deploy a virtual machine

**Comment by shinyzhu** [comment]
@IannaZhou 请问这两天可以完成吗？

**Comment by IannaZhou** [comment]
请给我两天时间。可以的，working on it

**Comment by shinyzhu** [comment]
@IannaZhou 这个文章很长，我从How do I instruct the Action?这里往下开始翻译吧。这样明天可以完成。谢谢。

**Comment by shinyzhu** [comment]
FYI: <https://github.com/azureselected/azureselected/blob/github-actions-deploy-vm/zh-cn/content/cloud-advocate/2020-02/how-to-use-github-actions-to-deploy-an-azure-virtual-machine.md>

**Comment by IannaZhou** [comment]
ok，谢谢！
