### ISSUE TITLE
The Best Way to Start With Azure Machine Learning

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#31]
原文：The Best Way to Start With Azure Machine Learning
链接：[/content/cloud-advocate/2020-02/the-best-way-to-start-with-azure-machine-learning.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-02/the-best-way-to-start-with-azure-machine-learning.md)

**Comment by yanxiaodi** [comment]
I can translate it.

**Comment by yanxiaodi** [comment]
#33 
Done.
