### ISSUE TITLE
The Secret Art of Debugging

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#32]
原文：The Secret Art of Debugging
链接：[/content/cloud-advocate/2020-02/the-secret-art-of-debugging.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-02/the-secret-art-of-debugging.md)

**Comment by cp8086** [comment]
认领这个吧

**Comment by cp8086** [comment]
[翻译稿.docx](https://github.com/azureselected/azureselected/files/4296695/default.docx)

**Comment by shinyzhu** [comment]
@cp8086 能按照GitHub的流程来吗？请参考[README.md](https://github.com/azureselected/azureselected/blob/master/README.md#%E7%BF%BB%E8%AF%91%E6%AD%A5%E9%AA%A4)

**Comment by shinyzhu** [comment]
@cp8086 我新建了分支把Word文档复制到markdown文件里了，请查看[这个单独分支的文件](https://github.com/azureselected/azureselected/blob/the-secret-art-of-debuging/zh-cn/content/cloud-advocate/2020-02/the-secret-art-of-debugging.md)。

<https://github.com/azureselected/azureselected/blob/the-secret-art-of-debuging/zh-cn/content/cloud-advocate/2020-02/the-secret-art-of-debugging.md>
