### ISSUE TITLE
How to Reduce the Costs of your Azure IaaS VMs

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#35]
原文：How to Reduce the Costs of your Azure IaaS VMs
链接：[/content/cloud-advocate/2020-02/how-to-reduce-the-costs-of-your-azure-iaas-vms.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-02/how-to-reduce-the-costs-of-your-azure-iaas-vms.md)

**Comment by dwz13612196385** [comment]
@shinyzhu 翻译认领 原文：How to Reduce the Costs of your Azure IaaS VMs
