### ISSUE TITLE
[翻译认领]how to reduce the costs of your azure iaas vms

### ISSUE THREAD

**Issue by DuanShaolong** [azureselected/azureselected#38]
认领时间： 2020-03-05
认领人员： Duan Shaolong
认领文章： how to reduce the costs of your azure iaas vms
原文：https://github.com/azureselected/azureselected/blob/master/zh-cn/content/cloud-advocate/2020-02/how-to-reduce-the-costs-of-your-azure-iaas-vms.md
目录：[content/cloud-advocate/](https://github.com/azureselected/azureselected/)

**Comment by shinyzhu** [comment]
建议不要新开，直接在原文的下面评论认领即可：#35
