### ISSUE TITLE
A Modern Developer's Workflow For Twine

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#44]
原文：A Modern Developer's Workflow For Twine
目录：[/content/cloud-advocate/2020-03/a-modern-developer-s-workflow-for-twine.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-03/a-modern-developer-s-workflow-for-twine.md)
计划完成时间：2020-03-31

**Comment by DuanShaolong** [comment]
翻译认领： A Modern Developer's Workflow For Twine
认领时间： 2020-03-17
原文：https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-03/a-modern-developer-s-workflow-for-twine.md

**Comment by shinyzhu** [comment]
#50
