### ISSUE TITLE
Getting Started With AzureML Notebook VMs

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#46]
原文：Getting Started With AzureML Notebook VMs
目录：[/content/cloud-advocate/2020-03/getting-started-with-azureml-notebook-vms.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-03/getting-started-with-azureml-notebook-vms.md)
计划完成时间：2020-04-05

**Comment by JamesL20** [comment]
I'd like to translate this one.
