### ISSUE TITLE
Create Your First Model with Custom Vision and Python

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#47]
原文：Create Your First Model with Custom Vision and Python
目录：[/content/cloud-advocate/2020-03/create-your-first-model-with-azure-custom-vision-and-python.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-03/create-your-first-model-with-azure-custom-vision-and-python.md)
计划完成时间：2020-04-05

**Comment by yanxiaodi** [comment]
I can do it.

**Comment by shinyzhu** [comment]
#53
