### ISSUE TITLE
9 Advanced Tips for Production Machine Learning

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#48]
原文：9 Advanced Tips for Production Machine Learning
目录：[/content/cloud-advocate/2020-03/9-advanced-tips-for-production-machine-learning.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-03/9-advanced-tips-for-production-machine-learning.md)
计划完成时间：2020-04-05

**Comment by ElderJames** [comment]
Applying for this Job.

**Comment by shinyzhu** [comment]
催更啦。
