### ISSUE TITLE
Creating Generative Art using GANs on Azure ML

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#54]
原文：https://soshnikov.com/scienceart/creating-generative-art-using-gan-on-azureml/
目录：[content/cloud-advocate/2020-04/creating-generative-art-using-gan-on-azureml.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-04/creating-generative-art-using-gan-on-azureml.md)
计划完成日期：2020-04-26

**Comment by DuanShaolong** [comment]
翻译认领： Creating Generative Art using GANs on Azure ML
认领时间： 2020-04-17
