### ISSUE TITLE
Build, test, and deploy .NET Core apps

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#56]
标题：Build, test, and deploy .NET Core apps
目录：[content/cloud-advocate/2020-05/build-test-and-deploy-dotnet-core-apps.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-05/build-test-and-deploy-dotnet-core-apps.md)
计划完成日期：2020-06-15
本文来自微软Docs，在完成审阅后可以直接发送PR到Docs。请参考：<https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md>

**Comment by DuanShaolong** [comment]
翻译认领：Build, test, and deploy .NET Core apps
认领时间： 2020-06-02
