### ISSUE TITLE
Build ASP.NET apps with .NET Framework

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#57]
原文：Build ASP.NET apps with .NET Framework
目录：[content/cloud-advocate/2020-05/build-aspnet-apps-with-dotnet-framework.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-05/build-aspnet-apps-with-dotnet-framework.md)
计划完成日期：2020-06-15
本文来自微软Docs，在完成审阅后可以直接发送PR到Docs。请参考：<https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md>

**Comment by DuanShaolong** [comment]
翻译认领：Build ASP.NET apps with .NET Framework
认领时间： 2020-07-10
