### ISSUE TITLE
Great new features in C# for a returning .NET dev

### ISSUE THREAD

**Issue by shinyzhu** [azureselected/azureselected#58]
原文：Great new features in C# for a returning .NET dev
目录：[content/cloud-advocate/2020-05/great-new-features-in-c-for-a-returning-net-dev.md](https://github.com/azureselected/azureselected/blob/master/content/cloud-advocate/2020-05/great-new-features-in-c-for-a-returning-net-dev.md)
计划完成日期：2020-06-15

**Comment by yanxiaodi** [comment]
我来这个吧

**Comment by yanxiaodi** [comment]
Done.
